apiVersion: v1
kind: Pod
metadata:
  name: adw-demo-pod
  labels:
    app: adwDemoApp
spec:
  containers:
    - name: adw-demo-container
      image: kix.ocir.io/hktwlab/adw-demo:v1.0.0
      ports:
        - containerPort: 80
