apiVersion: v1
kind: Service
metadata:
  name: adw-demo-lb-service
spec:
  type: LoadBalancer
  selector:
    app: adwDemoApp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30390
