apiVersion: apps/v1
kind: Deployment
metadata:
  name: adw-demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: adwDemoApp
    spec:
      containers:
        - name: adw-demo-container
          image: iad.ocir.io/idbj8ixgg36y/docker/adw-demo:v1.0.1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: adwDemoApp
